# EquivariantGNN model configuration - to be used with config_base.yaml
# Usage: python trainer.py fit --config config_base.yaml --config config_eq_gnn.yaml

model:
  class_path: EquivariantE3NN
  init_args:
    lr: 1e-2
    weight_decay: 0
    dropout: 0

data:
  data_dir: "data/processed_sh2"