# Override config to enable Weights & Biases logging
# Usage: python trainer.py fit --config config_base.yaml --config config_basic_gnn_augmented.yaml --config config_wandb.yaml

trainer:
  # Enable Weights & Biases logger
  logger:
    class_path: lightning.pytorch.loggers.WandbLogger
    init_args:
      project: "gnn-center-of-mass"
      name: "basic-gnn-augmented"
      save_dir: "wandb_logs"
      log_model: "all"  # Log model checkpoints to W&B
      tags: ["basic-gnn", "augmented", "center-of-mass"] 