# Centroid Baseline configuration - to be used with config_base.yaml
# Usage: python trainer.py fit --config config_base.yaml --config config_centroid_baseline.yaml

model:
  class_path: CentroidBaseline
  init_args: {}

# Data configuration - Use pointcloud data directly
data:
  class_path: src.data.pointcloud_baseline_data.PointCloudBaselineDataModule
  init_args:
    data_dir: "data/pointclouds"
    batch_size: 16
    val_split: 0.2
    num_workers: 0
