# EquivariantGNN model configuration - to be used with config_base.yaml
# Usage: python trainer.py fit --config config_base.yaml --config config_eq_gnn.yaml

model:
  class_path: EquivariantGNN
  init_args:
    lr: 1e-2
    weight_decay: 0
    multiplicity: 2
    message_passing_steps: 3
    max_sh_degree: 2
    base_l_values: [0, 1, 2]
    num_cg_layers: 2
    final_mlp_dims: [64, 32]
    dropout: 0
    debug: false

data:
  data_dir: "data/processed_sh2"