model:
  class_path: ImprovedBasicGNN
  init_args:
    lr: 1e-3
    weight_decay: 1e-5
    hidden_dim: 16
    message_passing_steps: 2
    edge_dim: 3
    final_mlp_dims: [32, 16]
    message_mlp_dims: [32, 16]
    dropout: 0.1
    seed: 42

trainer:
  max_epochs: 100
  check_val_every_n_epoch: 1
  log_every_n_steps: 10 