defaults:
  - override hydra/job_logging: disabled

trainer:
  max_epochs: 10
  devices: 1          # Number of devices (1 for CPU or GPU)
  accelerator: "cpu"  # Change to "gpu" if you have a GPU available

model:
  learning_rate: 0.001
  batch_size: 32
  num_points: 1024

data:
  path: data/lidar

seed: 42
