name: gnn_baseline
description: Baseline GNN model for center of mass estimation

defaults:
  - models/_models
  - models/gnn
  - training/_training
  - preprocessing/_preprocessing
  - preprocessing/lidar
  - preprocessing/graph
  - preprocessing/split
  - models: gnn
  - training: _training
  - preprocessing: _preprocessing
  - _self_

# Path to the LightningModule class to use
model:
  module_path: src.model.lightning_module.GNNLightningModule

seed: 42

# Hydra configuration settings
hydra:
  run:
    dir: logs/${name}/${now:%Y-%m-%d_%H-%M-%S}
  sweep:
    dir: logs/${name}_sweep/${now:%Y-%m-%d_%H-%M-%S}
    subdir: ${hydra.job.num}
  job_logging:
    handlers:
      file:
        filename: hydra.log