# debug.yaml - Quick debugging configuration
# @package _global_

defaults:
  - config  # Base config
  - _self_

# Override name for debug runs
name: "debug_equivariant_gnn"

# Enable debugging flags
fast_dev_run: 5  # Run only 5 batches of train/val/test
# Alternative debugging options (comment/uncomment as needed):
# limit_train_batches: 0.1    # Use only 10% of training data
# limit_val_batches: 0.1      # Use only 10% of validation data  
# overfit_batches: 10         # Overfit on 10 batches

# Reduce training parameters for debugging
training:
  max_epochs: 3
  batch_size: 4
  check_val_every_n_epoch: 1
  enable_wandb: false  # Disable wandb for debug runs

# Reduce model complexity for debugging  
models:
  gnn:
    hidden_dim: 8
    message_passing_steps: 1
    final_mlp_dims: [16]
    max_sh_degree: 1

# Use current directory for debugging
preprocessing:
  processed_dir: "data/processed" 