# Preprocessing-only configuration file
name: preprocessing_only
description: Standalone preprocessing pipeline

defaults:
  - preprocessing/_preprocessing
  - preprocessing/lidar
  - preprocessing/graph
  - preprocessing/split
  - _self_

# Basic settings
seed: 42
debug: false
use_optimized_preprocessing: true

# Hydra configuration settings
hydra:
  run:
    dir: logs/preprocessing/${now:%Y-%m-%d_%H-%M-%S}
  job_logging:
    handlers:
      file:
        filename: preprocessing.log
