# Configuration for scripts/visualize_equivariance.py

# Path to the trained model checkpoint
# NOTE: Using underscores instead of equals for compatibility if overriding via CLI.
# Ensure the actual file exists at checkpoints/se3_equivariant_v2-epoch=24-val_loss=0.1151.ckpt
checkpoint_path: checkpoints\se3_equivariant_v2_final.ckpt #checkpoints\se3_equivariant_v2-epoch=24-val_loss=0.1151.ckpt

# Python path to the LightningModule class used for training
model:
  module_path: src.model.SE3_equivariant.GNNLightningModule # Should be correct

# Data configuration (should match training)
data:
  processed_dir: data/processed
  # No need for train/test split here, just the base dir

# Index of the sample from the test set to visualize
sample_index: 0

# GPU usage (0 for CPU, 1+ for GPU)
gpus: 1

# Hydra settings (optional, mainly for output directory if needed)
hydra:
  run:
    dir: outputs/${hydra.job.name}/${now:%Y-%m-%d_%H-%M-%S}
  job:
    name: equivariance_viz # Default job name 