model:
  class_path: src.model.eq_gnn.EquivariantGNN
  init_args:
    message_passing_steps: 2
    final_mlp_dims: [64, 32]
    message_mlp_dims: [64, 32]
    edge_sh_degree: 2
    init_method: xavier
    seed: 42
    debug: false  # Disable debug mode
    lr: 1e-3
    weight_decay: 1e-5
    node_multiplicity: 3
    dropout: 0.02
    node_l_values: [0, 1, 2]