trainer:
  logger:
    class_path: lightning.pytorch.loggers.WandbLogger
    init_args:
      project: "gnn-center-of-mass"
      name: "eq_gnn"  # Specific name for Basic GNN
      save_dir: "wandb_logs"
      log_model: "all"
  callbacks+:
    - class_path: lightning.pytorch.callbacks.ModelCheckpoint
      init_args:
        dirpath: "checkpoints"
        filename: "eq_gnn-{epoch:02d}-{val_displacement_distance_epoch:.4f}"
        monitor: "val_displacement_distance_epoch"
        mode: "min"
        save_top_k: 1
        verbose: true 