model:
  class_path: FairComparisonGNN
  init_args:
    lr: 1e-3
    weight_decay: 1e-5
    node_features_dim: 11  # [x,y,z,x²,y²,z²,xy,xz,yz,‖x‖,‖x‖²]
    message_mlp_dims: [64, 32]
    final_mlp_dims: [64, 32]
    dropout: 0.02
    seed: 42 